load("@rules_pkg//pkg:mappings.bzl", "pkg_filegroup")

pkg_filegroup(
    name = "icons",
    srcs = [
        "//static/icons/android",
        "//static/icons/ios",
        "//static/icons/windows11",
    ],
    visibility = ["//static:__pkg__"],
)
