name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build
        run: bazel build //util:package

      - name: Output build checksum
        run: cat bazel-bin/util/checksum.txt > $GITHUB_OUTPUT

      - name: Extract tar
        run: |
          mkdir dist
          tar -xvf bazel-bin/util/package.tar -C dist

      - name: Upload pages
        uses: actions/upload-pages-artifact@master
        with:
          path: dist

  deploy:
    name: Deploy

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
